server:
  port: 8083
spring:
  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest
      routing-key:
        producer: rk.producer.service-broker

